# ============================================================
# IMPORT LIBRARIES
# ============================================================

import streamlit as st          # Dashboard UI
import plotly.express as px     # Interactive charts

# Import custom functions
from utils.load_data import load_data
from utils.filters import sidebar_filters


# ============================================================
# LOAD DATA
# ============================================================

# Load dataset
df = load_data()

# Apply sidebar filters selected by user
df = sidebar_filters(df)

st.set_page_config(
    page_title="Payment Analysis",
    page_icon="🍽️",
    layout="wide"
)

# Stop execution if filtered dataframe is empty
if df.empty:
    st.warning("⚠️ No data available for selected filters.")
    st.stop()


# ============================================================
# PAGE HEADER
# ============================================================

st.markdown("""
<div style='
    padding:25px;
    border-radius:20px;
    background:linear-gradient(135deg,#111827,#1E293B);
    border:1px solid rgba(255,255,255,0.08);
'>

<h1 style='color:white;'>💳 Payment Intelligence</h1>

<p style='color:#94A3B8;font-size:18px;'>
Analyze payment trends, transaction preferences,
and revenue contribution by payment methods.
</p>

</div>
""", unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)


# ============================================================
# KPI CALCULATIONS
# ============================================================

# Total revenue generated
total_revenue = df["Total_Amount"].sum()

# Most frequently used payment method
top_payment_method = (
    df["Payment_Method"]
    .value_counts()
    .idxmax()
)

# Count unique payment methods used
unique_methods = df["Payment_Method"].nunique()

# Average transaction amount
avg_transaction = round(
    df["Total_Amount"].mean(),
    2
)


# ============================================================
# DISPLAY KPI CARDS
# ============================================================

c1, c2, c3, c4 = st.columns(4)

c1.metric(
    "💰 Total Revenue",
    f"₹{total_revenue:,.0f}"
)

c2.metric(
    "🏆 Preferred Method",
    top_payment_method
)

c3.metric(
    "💳 Payment Methods",
    unique_methods
)

c4.metric(
    "🧾 Avg Transaction",
    f"₹{avg_transaction}"
)

st.markdown("---")


# ============================================================
# PAYMENT METHOD DISTRIBUTION
# ============================================================

# Shows percentage share of each payment method

fig = px.pie(
    df,

    # Categories
    names="Payment_Method",

    # Size of slices
    values="Total_Amount",

    # Donut chart
    hole=0.55,

    title="💳 Payment Method Distribution",

    color_discrete_sequence=px.colors.sequential.Tealgrn
)

fig.update_layout(
    template="plotly_dark"
)

fig.update_traces(
    textinfo="percent+label"
)

st.plotly_chart(
    fig,
    use_container_width=True
)


# ============================================================
# REVENUE BY PAYMENT METHOD
# ============================================================

# Calculate total revenue generated by each payment type

payment_revenue = (
    df.groupby("Payment_Method")["Total_Amount"]
      .sum()
      .reset_index()
      .sort_values(
          by="Total_Amount",
          ascending=False
      )
)

fig = px.bar(

    payment_revenue,

    x="Payment_Method",
    y="Total_Amount",

    color="Total_Amount",

    title="💰 Revenue Contribution by Payment Method",

    color_continuous_scale="Viridis"
)

fig.update_layout(
    template="plotly_dark",
    coloraxis_showscale=False
)

st.plotly_chart(
    fig,
    use_container_width=True
)


# ============================================================
# PAYMENT TREND OVER TIME
# ============================================================

# Group monthly revenue by payment method

monthly_payment = (

    df.groupby(
        [
            "Month",
            "Payment_Method"
        ]
    )["Total_Amount"]

    .sum()
    .reset_index()
)

# Multi-line chart

fig = px.line(

    monthly_payment,

    x="Month",
    y="Total_Amount",

    color="Payment_Method",

    markers=True,

    title="📈 Monthly Payment Trends"
)

fig.update_layout(
    template="plotly_dark"
)

st.plotly_chart(
    fig,
    use_container_width=True
)


# ============================================================
# TRANSACTION VALUE DISTRIBUTION
# ============================================================

# Shows spread of transaction amounts

fig = px.box(

    df,

    x="Payment_Method",

    y="Total_Amount",

    color="Payment_Method",

    title="📦 Transaction Amount Distribution"
)

fig.update_layout(
    template="plotly_dark"
)

st.plotly_chart(
    fig,
    use_container_width=True
)


# ============================================================
# HEATMAP DATA PREPARATION
# ============================================================

# Create pivot table

heatmap_data = (

    df.pivot_table(

        index="Payment_Method",
        columns="Month",

        values="Total_Amount",

        aggfunc="sum"
    )

    .fillna(0)
)

# Heatmap visualization

fig = px.imshow(

    heatmap_data,

    text_auto=True,

    aspect="auto",

    color_continuous_scale="Viridis",

    title="🔥 Revenue Heatmap by Payment Method"
)

fig.update_layout(
    template="plotly_dark"
)

st.plotly_chart(
    fig,
    use_container_width=True
)


# ============================================================
# EXECUTIVE SUMMARY
# ============================================================

st.subheader("📌 Executive Summary")

# Highest revenue payment method

best_method = (
    payment_revenue
    .iloc[0]["Payment_Method"]
)

best_method_revenue = (
    payment_revenue
    .iloc[0]["Total_Amount"]
)

st.info(f"""
🏆 Most Preferred Payment Method:
**{best_method}**

💰 Revenue Generated by {best_method}:
**₹{best_method_revenue:,.0f}**

🧾 Average Transaction Value:
**₹{avg_transaction}**

💳 Total Payment Methods Used:
**{unique_methods}**
""")